###read all users
GET http://localhost:4000/user-api/users



### read a peticular user
GET http://localhost:4000/user-api/user



### create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
 "username":"venky",
 "password":"venky",
 "email":"venky@gmail",
 "age":20
}

###update user
PUT http://localhost:4000/user-api/users/69ac26d203333321c16be61a
Cookie: Token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZlbmt5QGdtYWlsIiwiaWF0IjoxNzcyODg5MTI0LCJleHAiOjE3NzI4OTExMjR9.6FQL105Vzf9RGHdgp8eQEAF9VLx8bv6msyuPhkK9jDs; Path=/; HttpOnly; SameSite=La
Content-Type: application/json

{
"username":"tharun",
 "password":"tharun@gmail",
 "email":"tharun@mail",
 "age":21
}


###//delete user
DELETE http://localhost:4000/user-api/users/69ac2413f92dde74764198c3

###//userLogin
POST http://localhost:4000/user-api/auth
Content-Type: application/json

{  "email":"venky@gmail",
   "password":"venky"

}

###add products to cart
PUT http://localhost:4000/user-api/cart/product-id/69b249964e353440776a45d2

###product creation
POST http://localhost:4000/product-api/product
Content-Type: application/json

{
    "productId":2,
    "productName":"Laptop",
    "price":45000,
    "brand":"Hp"
}

###
GET http://localhost:4000/product-api/product

###
GET http://localhost:4000/product-api/product/69ab169456974260ce62c53b

###
PUT http://localhost:4000/product-api/product/69ab099786d7b83d3d4899ec
Content-Type: application/json

{   "productId":1,
    "productName":"Laptop",
    "price":49000,
    "brand":"Mi"

}

###
DELETE http://localhost:4000/product-api/product/69ab099786d7b83d3d4899ec
