###read all users
GET http://localhost:2306/user-api/users

### read a peticular user
GET http://localhost:2306/user-api/users/2

### create user
POST http://localhost:2306/user-api/users
Content-Type: application/json

{
    "id":2,
    "name":"Ganesh",
    "age":25
}

###update user
PUT http://localhost:2306/user-api/users
Content-Type: application/json

{
    "id":2,
    "name":"venkat",
    "age":20
}


###//delete user
DELETE http://localhost:2306/user-api/users/2


###
POST http://localhost:2306/product-api/product
Content-Type: application/json

{
    "id":2,
    "Name":"Laptop",
    "Brand":"Hp",
    "Price":6000
}

###
GET http://localhost:2306/product-api/product

###
PUT http://localhost:2306/product-api/product
Content-Type: application/json

{
    "id":2,
    "Name":"Laptop",
    "Brand":"Hp",
    "Price":50000
}

###
DELETE http://localhost:2306/product-api/product1

###
GET http://localhost:2306/product-api/product/2